In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [2]:
crop=pd.read_csv('D://MachineLearning/CropRecommendation.csv')

In [3]:
crop

,N_SOIL,P_SOIL,K_SOIL,TEMPERATURE,HUMIDITY,ph,RAINFALL,STATE,CROP
0,90,42,43,20.879744,82.002744,6.502985,202.935536,Andaman and Nicobar,Rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,Andaman and Nicobar,Rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,Andaman and Nicobar,Rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,Andaman and Nicobar,Rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,Andaman and Nicobar,Rice
...,...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,West Bengal,Coffee
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,West Bengal,Coffee
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,West Bengal,Coffee
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,West Bengal,Coffee
2199,104,18,30,23.603016,60.396475,6.779833,140.937041,West Bengal,Coffee

In [4]:
crop=crop.dropna(axis=1)

In [5]:
crop

,N_SOIL,P_SOIL,K_SOIL,TEMPERATURE,HUMIDITY,ph,RAINFALL,STATE,CROP
0,90,42,43,20.879744,82.002744,6.502985,202.935536,Andaman and Nicobar,Rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,Andaman and Nicobar,Rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,Andaman and Nicobar,Rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,Andaman and Nicobar,Rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,Andaman and Nicobar,Rice
...,...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,West Bengal,Coffee
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,West Bengal,Coffee
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,West Bengal,Coffee
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,West Bengal,Coffee
2199,104,18,30,23.603016,60.396475,6.779833,140.937041,West Bengal,Coffee

In [6]:
crop.shape

(2200, 9)

In [7]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N_SOIL       2200 non-null   int64
 1   P_SOIL       2200 non-null   int64
 2   K_SOIL       2200 non-null   int64
 3   TEMPERATURE  2200 non-null   float64
 4   HUMIDITY     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   RAINFALL     2200 non-null   float64
 7   STATE        2200 non-null   object
 8   CROP         2200 non-null   object
dtypes: float64(4), int64(3), object(2)
memory usage: 154.8+ KB

In [8]:
crop.isnull().sum()

N_SOIL         0
P_SOIL         0
K_SOIL         0
TEMPERATURE    0
HUMIDITY       0
ph             0
RAINFALL       0
STATE          0
CROP           0
dtype: int64

In [9]:
crop.duplicated().sum()

0

In [10]:
crop.describe()

,N_SOIL,P_SOIL,K_SOIL,TEMPERATURE,HUMIDITY,ph,RAINFALL
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [11]:
crop['CROP'].value_counts()

CROP
Rice           100
Maize          100
Jute           100
Cotton         100
Coconut        100
Papaya         100
Orange         100
Apple          100
Muskmelon      100
Watermelon     100
Grapes         100
Mango          100
Banana         100
Pomegranate    100
Lentil         100
Blackgram      100
MungBean       100
MothBeans      100
PigeonPeas     100
KidneyBeans    100
ChickPea       100
Coffee         100
Name: count, dtype: int64

In [12]:
crop['STATE'].value_counts()

STATE
Uttar Pradesh          574
Kerala                 274
Tamil Nadu             183
Punjab                 180
Maharashtra            162
West Bengal            124
Gujarat                113
Himachal Pradesh       102
Odisha                  86
Haryana                 65
Assam                   58
Manipur                 52
Madhya Pradesh          44
Rajasthan               41
Karnataka               36
Uttrakhand              21
Tripura                 18
Telangana               15
Andaman and Nicobar     15
Andhra Pradesh           7
Pondicherry              7
Meghalaya                6
Nagaland                 6
Chattisgarh              5
Jammu and Kashmir        3
Goa                      3
Name: count, dtype: int64

In [13]:
State=crop['STATE'].unique()
State

array(['Andaman and Nicobar', 'Andhra Pradesh', 'Assam', 'Chattisgarh',
       'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Karnataka', 'Kerala', 'Madhya Pradesh',
       'Maharashtra', 'Manipur', 'Meghalaya', 'Nagaland', 'Odisha',
       'Pondicherry', 'Punjab', 'Rajasthan', 'Tamil Nadu', 'Telangana',
       'Tripura', 'Uttar Pradesh', 'Uttrakhand', 'West Bengal'],
      dtype=object)

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
label_encode=LabelEncoder()

In [16]:
encoded_state = label_encode.fit_transform(crop['STATE']).astype('int32')
crop.loc[:, 'STATE'] = encoded_state

In [17]:
X=crop.drop(['CROP'],axis=1)
y=crop['CROP']

In [18]:
crop

,N_SOIL,P_SOIL,K_SOIL,TEMPERATURE,HUMIDITY,ph,RAINFALL,STATE,CROP
0,90,42,43,20.879744,82.002744,6.502985,202.935536,0,Rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,0,Rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,0,Rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,0,Rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,0,Rice
...,...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,25,Coffee
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,25,Coffee
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,25,Coffee
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,25,Coffee
2199,104,18,30,23.603016,60.396475,6.779833,140.937041,25,Coffee

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.3)

In [20]:
X_train

,N_SOIL,P_SOIL,K_SOIL,TEMPERATURE,HUMIDITY,ph,RAINFALL,STATE
1091,96,86,51,29.908885,76.987408,6.257370,91.999647,18
1175,31,36,29,33.936799,52.721703,6.460543,97.461192,18
422,16,55,19,19.543141,47.191883,6.413544,192.437219,10
514,23,45,21,31.465113,51.799394,8.985348,74.443307,10
1193,39,16,27,35.538450,52.946419,4.934965,91.545604,18
...,...,...,...,...,...,...,...,...
1245,31,136,197,31.110473,83.340110,5.653776,71.430016,19
574,39,42,20,29.349971,61.253539,8.055909,40.828407,10
63,70,36,42,21.841069,80.728864,6.946210,202.383832,2
734,39,60,21,34.898149,63.599486,6.972977,64.727971,12
1177,40,16,35,31.893563,49.024501,6.484152,89.593715,18

In [21]:
y_train

1091        Banana
1175         Mango
422     PigeonPeas
514      MothBeans
1193         Mango
           ...
1245        Grapes
574      MothBeans
63            Rice
734      Blackgram
1177         Mango
Name: CROP, Length: 1540, dtype: object

In [22]:
X_train

,N_SOIL,P_SOIL,K_SOIL,TEMPERATURE,HUMIDITY,ph,RAINFALL,STATE
1091,96,86,51,29.908885,76.987408,6.257370,91.999647,18
1175,31,36,29,33.936799,52.721703,6.460543,97.461192,18
422,16,55,19,19.543141,47.191883,6.413544,192.437219,10
514,23,45,21,31.465113,51.799394,8.985348,74.443307,10
1193,39,16,27,35.538450,52.946419,4.934965,91.545604,18
...,...,...,...,...,...,...,...,...
1245,31,136,197,31.110473,83.340110,5.653776,71.430016,19
574,39,42,20,29.349971,61.253539,8.055909,40.828407,10
63,70,36,42,21.841069,80.728864,6.946210,202.383832,2
734,39,60,21,34.898149,63.599486,6.972977,64.727971,12
1177,40,16,35,31.893563,49.024501,6.484152,89.593715,18

In [23]:
y_train

1091        Banana
1175         Mango
422     PigeonPeas
514      MothBeans
1193         Mango
           ...
1245        Grapes
574      MothBeans
63            Rice
734      Blackgram
1177         Mango
Name: CROP, Length: 1540, dtype: object

In [24]:
#USING DECISION TREE
from sklearn.metrics import accuracy_score
from sklearn import tree
decision_tree=tree.DecisionTreeClassifier()
decision_tree.fit(X_train,y_train)

DecisionTreeClassifier()

In [25]:
y_pred=decision_tree.predict(X_test)

In [26]:
y_pred

array(['Papaya', 'Blackgram', 'KidneyBeans', 'Orange', 'Apple', 'Cotton',
       'Orange', 'ChickPea', 'Maize', 'Blackgram', 'Pomegranate', 'Jute',
       'Cotton', 'Banana', 'Coffee', 'Maize', 'Grapes', 'KidneyBeans',
       'Lentil', 'MungBean', 'Pomegranate', 'Coffee', 'Jute', 'Mango',
       'Mango', 'Blackgram', 'Papaya', 'Apple', 'KidneyBeans', 'ChickPea',
       'ChickPea', 'KidneyBeans', 'Coffee', 'Banana', 'MungBean',
       'Lentil', 'Orange', 'ChickPea', 'Jute', 'Pomegranate', 'Banana',
       'KidneyBeans', 'Rice', 'Maize', 'Coconut', 'Jute', 'Apple',
       'MungBean', 'Watermelon', 'Grapes', 'Papaya', 'MungBean', 'Mango',
       'Jute', 'Lentil', 'Grapes', 'Cotton', 'MungBean', 'Watermelon',
       'Apple', 'ChickPea', 'Coffee', 'Banana', 'Jute', 'Coconut',
       'Mango', 'Rice', 'MungBean', 'Lentil', 'Watermelon', 'ChickPea',
       'Banana', 'Grapes', 'Cotton', 'Jute', 'Rice', 'Jute', 'Banana',
       'PigeonPeas', 'KidneyBeans', 'Maize', 'Muskmelon', 'Orange',
       'Banana', 'KidneyBeans', 'Grapes', 'MothBeans', 'Papaya',
       'Pomegranate', 'Jute', 'MothBeans', 'Maize', 'Grapes', 'Blackgram',
       'Coconut', 'Grapes', 'Muskmelon', 'Grapes', 'Papaya', 'Coffee',
       'KidneyBeans', 'PigeonPeas', 'ChickPea', 'MungBean', 'Rice',
       'Muskmelon', 'Coconut', 'MungBean', 'KidneyBeans', 'MothBeans',
       'ChickPea', 'ChickPea', 'Banana', 'Coffee', 'Banana', 'MungBean',
       'ChickPea', 'Grapes', 'Papaya', 'Maize', 'PigeonPeas', 'Blackgram',
       'Coffee', 'Rice', 'PigeonPeas', 'MungBean', 'Maize', 'Maize',
       'Banana', 'Cotton', 'Blackgram', 'Cotton', 'Grapes', 'PigeonPeas',
       'Coffee', 'Maize', 'Rice', 'PigeonPeas', 'Orange', 'Banana',
       'Blackgram', 'Apple', 'Jute', 'Muskmelon', 'ChickPea', 'Jute',
       'Maize', 'Coconut', 'Banana', 'Watermelon', 'PigeonPeas', 'Lentil',
       'Banana', 'PigeonPeas', 'Watermelon', 'Mango', 'Pomegranate',
       'Apple', 'Muskmelon', 'Banana', 'KidneyBeans', 'Cotton', 'Mango',
       'Apple', 'Jute', 'Coffee', 'Orange', 'Lentil', 'Lentil',
       'Watermelon', 'Banana', 'Coconut', 'Coffee', 'ChickPea', 'Apple',
       'Watermelon', 'Papaya', 'Blackgram', 'Muskmelon', 'Apple',
       'Cotton', 'KidneyBeans', 'Apple', 'Coffee', 'Blackgram', 'Grapes',
       'KidneyBeans', 'Cotton', 'Papaya', 'Banana', 'PigeonPeas', 'Rice',
       'Blackgram', 'Grapes', 'Mango', 'Papaya', 'Apple', 'Papaya',
       'Muskmelon', 'Banana', 'Watermelon', 'Banana', 'KidneyBeans',
       'Coconut', 'Rice', 'MungBean', 'Banana', 'Papaya', 'Coconut',
       'Coffee', 'ChickPea', 'Muskmelon', 'Lentil', 'Banana', 'Coconut',
       'Maize', 'Pomegranate', 'Orange', 'Grapes', 'Coconut', 'MothBeans',
       'Lentil', 'Grapes', 'MungBean', 'Rice', 'Watermelon',
       'KidneyBeans', 'Rice', 'MungBean', 'Mango', 'Rice', 'ChickPea',
       'Rice', 'Pomegranate', 'Cotton', 'Cotton', 'Watermelon', 'Apple',
       'Grapes', 'ChickPea', 'MothBeans', 'Coffee', 'Muskmelon',
       'Pomegranate', 'KidneyBeans', 'ChickPea', 'Mango', 'Apple',
       'Watermelon', 'Grapes', 'Maize', 'Pomegranate', 'Coffee', 'Maize',
       'MothBeans', 'Orange', 'Rice', 'Papaya', 'Muskmelon', 'Coffee',
       'MothBeans', 'Mango', 'Apple', 'Watermelon', 'Banana', 'MungBean',
       'Pomegranate', 'MungBean', 'Lentil', 'ChickPea', 'Lentil',
       'PigeonPeas', 'Coffee', 'Cotton', 'Jute', 'KidneyBeans', 'Lentil',
       'Grapes', 'Blackgram', 'Lentil', 'Coconut', 'Blackgram', 'Orange',
       'PigeonPeas', 'Jute', 'Maize', 'Orange', 'Coffee', 'Rice',
       'MungBean', 'Rice', 'PigeonPeas', 'Muskmelon', 'Grapes', 'Papaya',
       'MothBeans', 'Maize', 'Cotton', 'Papaya', 'Apple', 'Maize',
       'Muskmelon', 'Jute', 'Watermelon', 'Jute', 'MothBeans',
       'Muskmelon', 'Papaya', 'Papaya', 'Banana', 'Coconut', 'MothBeans',
       'Cotton', 'KidneyBeans', 'Pomegranate', 'Maize', 'Muskmelon',
       'Cotton', 'Muskmelon', 'Grapes', 'Muskmelon', 'Coconut', 'Rice',
       'Pomegranate', 'Jute', 'ChickPea', 'ChickPea', 'Papaya', 'Orange',
       'PigeonPeas', 'Maize', 'Watermelon', 'Cotton', 'MungBean',
       'Muskmelon', 'Watermelon', 'Rice', 'Apple', 'Coffee', 'Cotton',
       'Mango', 'ChickPea', 'MungBean', 'Mango', 'Maize', 'Blackgram',
       'Banana', 'Papaya', 'Muskmelon', 'MungBean', 'Muskmelon',
       'KidneyBeans', 'Jute', 'Banana', 'ChickPea', 'Cotton', 'Coconut',
       'Blackgram', 'Muskmelon', 'Rice', 'Lentil', 'Apple', 'Blackgram',
       'Lentil', 'ChickPea', 'Pomegranate', 'Mango', 'Pomegranate',
       'Blackgram', 'Orange', 'Banana', 'Papaya', 'Cotton', 'Jute',
       'Jute', 'Mango', 'Pomegranate', 'Rice', 'PigeonPeas', 'Orange',
       'Cotton', 'MothBeans', 'Coconut', 'Cotton', 'Orange',
       'KidneyBeans', 'KidneyBeans', 'Mango', 'Banana', 'Cotton', 'Mango',
       'ChickPea', 'Maize', 'MothBeans', 'Jute', 'Jute', 'MothBeans',
       'Maize', 'PigeonPeas', 'Jute', 'Lentil', 'PigeonPeas',
       'PigeonPeas', 'Jute', 'PigeonPeas', 'Orange', 'Muskmelon',
       'Coffee', 'Coconut', 'MungBean', 'Watermelon', 'MothBeans',
       'Coconut', 'Apple', 'PigeonPeas', 'Coffee', 'MungBean',
       'Blackgram', 'Papaya', 'ChickPea', 'Jute', 'Lentil', 'Cotton',
       'Apple', 'PigeonPeas', 'ChickPea', 'Orange', 'Rice', 'MungBean',
       'Coconut', 'MothBeans', 'MothBeans', 'Coffee', 'Muskmelon',
       'Watermelon', 'Maize', 'KidneyBeans', 'Cotton', 'Mango',
       'MothBeans', 'Blackgram', 'Mango', 'Coconut', 'Blackgram',
       'Coconut', 'Muskmelon', 'Pomegranate', 'Coconut', 'PigeonPeas',
       'Apple', 'MungBean', 'MungBean', 'Muskmelon', 'Mango', 'Coffee',
       'Pomegranate', 'ChickPea', 'Maize', 'Mango', 'Banana', 'Mango',
       'Blackgram', 'Cotton', 'Pomegranate', 'Cotton', 'ChickPea',
       'Pomegranate', 'Apple', 'Grapes', 'Maize', 'Rice', 'ChickPea',
       'MungBean', 'Muskmelon', 'ChickPea', 'Banana', 'Rice', 'MothBeans',
       'Lentil', 'MungBean', 'Pomegranate', 'Pomegranate', 'Mango',
       'Muskmelon', 'Papaya', 'Blackgram', 'Muskmelon', 'Grapes', 'Mango',
       'KidneyBeans', 'Banana', 'Coffee', 'Banana', 'Coconut', 'Banana',
       'MungBean', 'Cotton', 'ChickPea', 'Jute', 'Blackgram',
       'KidneyBeans', 'Lentil', 'Mango', 'Watermelon', 'Pomegranate',
       'Muskmelon', 'Rice', 'Apple', 'Cotton', 'Blackgram', 'Rice',
       'Pomegranate', 'KidneyBeans', 'MothBeans', 'Grapes', 'MothBeans',
       'Apple', 'Grapes', 'Maize', 'Coffee', 'Rice', 'Apple', 'MungBean',
       'Jute', 'Coffee', 'Watermelon', 'Blackgram', 'Maize', 'Coffee',
       'Mango', 'Rice', 'Coffee', 'Blackgram', 'Cotton', 'ChickPea',
       'Apple', 'Pomegranate', 'KidneyBeans', 'Muskmelon', 'Papaya',
       'Watermelon', 'Coffee', 'Papaya', 'Watermelon', 'Muskmelon',
       'Apple', 'Coffee', 'Watermelon', 'Watermelon', 'Maize', 'Orange',
       'Cotton', 'KidneyBeans', 'PigeonPeas', 'Grapes', 'Watermelon',
       'Pomegranate', 'MothBeans', 'Banana', 'Coconut', 'Pomegranate',
       'Banana', 'PigeonPeas', 'Muskmelon', 'Orange', 'MungBean',
       'Coffee', 'Maize', 'Coconut', 'Jute', 'Papaya', 'MothBeans',
       'MungBean', 'Blackgram', 'Muskmelon', 'Apple', 'Pomegranate',
       'Grapes', 'Blackgram', 'Apple', 'Maize', 'Muskmelon', 'MungBean',
       'PigeonPeas', 'Pomegranate', 'Cotton', 'Cotton', 'KidneyBeans',
       'KidneyBeans', 'Grapes', 'Cotton', 'Rice', 'PigeonPeas', 'Cotton',
       'PigeonPeas', 'Maize', 'Jute', 'Jute', 'KidneyBeans', 'Papaya',
       'Pomegranate', 'Cotton', 'Pomegranate', 'Muskmelon', 'Grapes',
       'Blackgram', 'Rice', 'Lentil', 'Coconut', 'Banana', 'Lentil',
       'ChickPea', 'Apple', 'Mango', 'Pomegranate', 'Maize',
       'Pomegranate', 'Jute', 'Rice', 'Watermelon', 'Blackgram',
       'Blackgram', 'Cotton', 'Papaya', 'Coconut', 'MungBean', 'Banana',
       'Lentil', 'Rice', 'ChickPea', 'Papaya', 'Mango', 'MungBean',
       'Apple', 'Jute', 'Blackgram', 'MothBeans', 'Apple', 'Lentil',
       'Blackgram', 'Blackgram', 'Pomegranate', 'Orange', 'Pomegranate',
       'MothBeans', 'Pomegranate', 'Coffee', 'Banana', 'Apple',
       'PigeonPeas', 'KidneyBeans', 'Muskmelon', 'Pomegranate', 'Orange',
       'Coffee', 'Maize', 'Lentil', 'Rice', 'Blackgram', 'PigeonPeas'],
      dtype=object)

In [27]:
accuracy_score(y_test,y_pred)

1.0

In [28]:
pickle.dump(decision_tree, open('crop_model.pkl', 'wb'))
pickle.dump(label_encode, open('label_encode.pkl', 'wb'))